export const boardControlsConfig = {
  boardWidth: {
    value: 2.0,
    min: 0.5,
    max: 10,
    step: 0.01,
    label: "Ширина дошки",
  },
  boardHeight: {
    value: 2.0,
    min: 0.5,
    max: 10,
    step: 0.01,
    label: "Висота дошки",
  },
  boardDepth: {
    value: 0.05,
    min: 0.01,
    max: 0.2,
    step: 0.01,
    label: "Товщина дошки",
  },
  spacing: {
    value: 3,
    min: 0,
    max: 10,
    step: 0.1,
    label: "Відстань між дошками",
  },
  glowBoxScaleX: {
    value: 1.09,
    min: 1,
    max: 2,
    step: 0.01,
    label: "Glow Box X",
  },
  glowBoxScaleY: {
    value: 1.09,
    min: 1,
    max: 2,
    step: 0.01,
    label: "Glow Box Y",
  },
  glowBoxScaleZ: {
    value: 1.01,
    min: 1,
    max: 2,
    step: 0.01,
    label: "Glow Box Z",
  },
  gradColor1: { value: "#268baa", label: "Градієнт центр" },
  gradColor2: { value: "#213e52", label: "Градієнт зовнішній" },
  gradRadius: {
    value: 1.6,
    min: -1,
    max: 2,
    step: 0.1,
    label: "Радіус градієнта",
  },
  gradCenterX: { value: 1, min: -1, max: 1, step: 0.01, label: "Центр X" },
  gradCenterY: { value: -1, min: -1, max: 1, step: 0.01, label: "Центр Y" },
  gradColor1Active: { value: "#94c5e8", label: "Градієнт центр (активна)" },
  gradColor2Active: { value: "#2c7da0", label: "Градієнт зовнішній (активна)" },
  gradRadiusActive: {
    value: 1.0,
    min: -1,
    max: 2,
    step: 0.1,
    label: "Радіус градієнта (активна)",
  },
  gradCenterXActive: {
    value: 0.1,
    min: -1,
    max: 1,
    step: 0.01,
    label: "Центр X (активна)",
  },
  gradCenterYActive: {
    value: -1,
    min: -1,
    max: 1,
    step: 0.01,
    label: "Центр Y (активна)",
  },
  edgeActiveColor: { value: "#a6daff", label: "Колір ребер" },
  edgeColor: { value: "#0d3857", label: "Колір активних ребер" },
  lightIntensity: {
    value: 0.5,
    min: 0,
    max: 2,
    step: 0.01,
    label: "Ambient Light",
  },
  dirLightIntensity: {
    value: 1.46,
    min: 0,
    max: 2,
    step: 0.01,
    label: "Directional Light",
  },
  glowColor: { value: "#58a1c1", label: "Світіння (active)" },
  glowStrength: {
    value: 1.49,
    min: 0,
    max: 3,
    step: 0.01,
    label: "Сила світіння",
  },
  glowBlur: {
    value: 0.5,
    min: 0.5,
    max: 5,
    step: 0.01,
    label: "Розмитість світіння",
  },
  glowIntensity: {
    value: 0.92,
    min: 0,
    max: 2,
    step: 0.01,
    label: "Інтенсивність світіння",
  },
  glowRadiusX: {
    value: 0.2,
    min: 0.1,
    max: 0.5,
    step: 0.01,
    label: "Радіус світіння X",
  },
  glowHeightX: {
    value: 1,
    min: 0.1,
    max: 2,
    step: 0.01,
    label: "Висота світіння X",
  },
  glowRadiusY: {
    value: 0.1,
    min: 0.1,
    max: 0.5,
    step: 0.01,
    label: "Радіус світіння Y",
  },
  glowWidthY: {
    value: 0.1,
    min: 0.1,
    max: 2,
    step: 0.01,
    label: "Ширина світіння Y",
  },
  opacity: {
    value: 0.6,
    min: 0,
    max: 1,
    step: 0.01,
    label: "Прозорість дошки",
  },
};
